const YOUR_TELEGRAM_TOKEN = '770337251:AAGwmMvfkjzOCUeujjIbcX1ksy6OY0A2gU4';
const YOUR_JAMBLER_API_KEY = 'w9nyw7EytYd1xJj9hZI1BpxGUVX';
/* ===== TOKENS ===== */
const TELEGRAM_BOT_API_TOKEN = process.env.TELEGRAM_API_TOKEN == null ? YOUR_TELEGRAM_TOKEN: process.env.TELEGRAM_API_TOKEN;
const PARTNER_API_TOKEN = process.env.PARTNER_API_TOKEN == null ? YOUR_JAMBLER_API_KEY : process.env.PARTNER_API_TOKEN;

/* ===== TECHNICAL ===== */
const BACKEND_URL = 'https://api.jambler.io';
const CACHE_TTL = 10 * 60;
const PARSE_MODE = 'html';
const COIN_ID = 'btc';
const MAX_DDOS_HITS = 2;

/* ===== PAGE RESOURCES ===== */

const FAQ_PAGE =
`<strong>Q:</strong> What is the minimum and maximum amount you accept for cleansing?
<strong>A:</strong> From 0.001 up to 50 BTC.

<strong>Q:</strong> How many confirmations do you require on my incoming transfer?
<strong>A:</strong> We start processing your order after the first confirmation.

<strong>Q:</strong> How much time do I have to send my coins after placing a mixing request?
<strong>A:</strong> The input address we give you will remain valid for 7 days after your request.

<strong>Q:</strong> What logs do you store?
<strong>A:</strong> None, only the temporary data required to process your order, and only until it is completed.

<strong>Q:</strong> If so, then how can I prove I sent you coins if something goes wrong?
<strong>A:</strong> After placing your request, we send you our PGP-signed letter of guarantee, containing all the details of our deal, including the input address for your coins. Save and keep this letter; it will be an infallible proof of our obligations in case you suspect any malfunction or fraud.`;

const CONTACT_US_PAGE =
`<strong>Clearnet:</strong> https://jambler.io
<strong>Tor:</strong> jambler2zgfnjykq.onion
<strong>Email:</strong> support@jambler.io
<strong>Reddit:</strong> reddit.com/user/Jambler_io
<strong>Bitcoin Talk:</strong> bitcointalk.org/index.php?topic=4667343`;

const DDOS_PROTECTION_PAGE = `DDOS_PROTECTION`;

/* ===== COMMAND TEXT RESOURCES ===== */
const START_COMMAND = `<strong>Start</strong>`;
const HELP_COMMAND = `<strong>Commands:</strong>\n/start\n/help`;
const UNHANDLED_COMMAND = `<strong>Unhandled</strong>`;

/* ===== BUTTON TEXTS ===== */
const MIX_MY_COINS = 'Mix My Coins';
const FAQ = 'FAQ';
const FEE = 'Fee';
const CONTACT_US = 'Contact Us';
const CANCEL_MIXING = 'Cancel Mixing';
const START_MIXING = 'Start Mixing';

/* ===== KEYBOARDS ===== */
const STANDARD_KEYBOARD = [
  [{ text: MIX_MY_COINS}, { text: FAQ}],
  [{ text: FEE }, { text: CONTACT_US }]
];
const MIXING_KEYBOARD = [[{ text: START_MIXING}, { text: CANCEL_MIXING }]];

/* ===== COMBINED MESSAGES ===== */
const MainMenuMessage = (Variables) => `${Variables.MIXER_NAME}\nWelcome. We are an innovative, premium level bitcoin mixer. Receive clean coins from cryptocurrency stock exchanges around the globe.\nCommission: ${Variables.MIXER_FEE_PCT}% + ${Variables.MIXER_FIX_FEE} BTC\nCleansing time: up to ${Variables.WITHDRAW_MAX_TIMEOUT} hours.\nA unique anonymization algorithm.\n<strong>Clearnet:</strong> https://jambler.io\n<strong>Tor:</strong> jambler2zgfnjykq.onion`;
const FeeMenuMessage = (Variables) => `The maximum commission is ${Variables.MIXER_FEE_PCT}% + ${Variables.MIXER_FIX_FEE} BTC.\nThe minimal amount for cleansing is ${Variables.MIN_AMOUNT} BTC; the maximum is ${Variables.MAX_AMOUNT} BTC.\nThe input address generated by the mixer will be available for ${Variables.ORDER_LIFETIME} hours (${Variables.ORDER_LIFETIME / 24} days)\nThe cleansing time is up to ${Variables.WITHDRAW_MAX_TIMEOUT} hours, starting from the first confirmation of your incoming transfer.\nCleansed coins will arrive at your output address(es) in parts at random times within this period.`;
const SendToAddress = (Variables) => `Please send your coins (min ${Variables.MIN_AMOUNT} BTC, max ${Variables.MAX_AMOUNT} BTC) at:`;
const AddressAvailability = (Variables) => `\nThis address will be available for ${Variables.ORDER_LIFETIME} hours (${Variables.ORDER_LIFETIME / 24} days). Cleansing time is up to ${Variables.WITHDRAW_MAX_TIMEOUT} hours. The commission is up to ${Variables.MIXER_FEE_PCT}%, + ${Variables.MIXER_FIX_FEE} BTC»`;

/* ===== SIMPLE MESSAGES ===== */
const UNHANDLED_MIXING_ERROR = `Unknown error.`;
const ENTER_FIRST_BTC_WALLET = `Please enter your BTC forward address.`;
const ENTER_SECOND_BTC_WALLET = `If you wish to use a second forward address, please enter it now. Otherwise, click ${START_MIXING}.`;
const NOT_VALID_ADDRESS = `The text you sent is not a valid BTC address. Please try again or try a different address.`;
const GUARANTEE_LETTER_HEADER = `<strong>Your guarantee letter. Please save and keep it until your order is fully processed.</strong>`;

module.exports = {
  TELEGRAM_BOT_API_TOKEN,
  PARTNER_API_TOKEN,
  BACKEND_URL,
  CACHE_TTL,
  PARSE_MODE,
  COIN_ID,
  MAX_DDOS_HITS,
  Keyboards: {
    STANDARD_KEYBOARD,
    MIXING_KEYBOARD
  },
  Resources: {
    Keyboard: {
      START_MIXING,
      CANCEL_MIXING,
      MIX_MY_COINS,
      FAQ,
      FEE,
      CONTACT_US
    },
    Markups: {
      STANDARD: STANDARD_KEYBOARD,
      MIXING: MIXING_KEYBOARD,
    },
    Pages: {
      FAQ_PAGE,
      CONTACT_US_PAGE,
      
    },
    Commands: {
      START_COMMAND,
      HELP_COMMAND,
      UNHANDLED_COMMAND
    },
    Messages: {
      UNHANDLED_MIXING_ERROR,
      ENTER_FIRST_BTC_WALLET,
      ENTER_SECOND_BTC_WALLET,
      NOT_VALID_ADDRESS,
      GUARANTEE_LETTER_HEADER,
      SendToAddress,
      AddressAvailability,
      MainMenuMessage,
      FeeMenuMessage,
      DDOS_PROTECTION_PAGE
    },
    Variables: {
      MIN_AMOUNT: 1,
      MAX_AMOUNT: 2,
      ORDER_LIFETIME: 48,
      WITHDRAW_MAX_TIMEOUT: 48,
      MIXER_FEE_PCT: 10,
      MIXER_FIX_FEE: 10
    }
  }
}
